name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Enable corepack
      run: corepack enable
    - name: Install modules
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Run tests
      run: yarn test
