name: Publish documentation to GH Pages

on:
  push:
    branches:
      - 'master'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: "Cache dependencies"
      uses: actions/cache@v2
      with:
        path: docs/node_modules
        key: ${{ runner.os }}build-node-${{ hashFiles('docs/yarn.lock') }}
        restore-keys: ${{ runner.os }}-build-node-

    - name: "Install documentation dependencies"
      run: yarn --cwd docs install --frozen-lockfile

    - name: "Build documentation"
      run: yarn --cwd docs vuepress build .

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/.vuepress/dist
        cname: vue-sliding-pagination.efrane.com
